#!/usr/bin/env python3
import re
import sys


new_line = ''
gene_list = []

for files in sys.argv[1:]:
	with open(files, 'r') as input_file, open('GO'+files+'.txt', 'w') as output_file:
		for line in input_file:
			line = line.rstrip()
			line = line.replace("|","X")
			line = re.sub(r".+X","",line)
			line = re.sub(r"-.+","",line)
			line = line.upper()
			line = line+'_HUMAN'
			output_file.write(line+'\n')
	string = 'Successfully converted {} to GO{}.txt'
	final_string = string.format(files,files)
	print(final_string)
		
